language: cpp

matrix:
  include:

    - os: linux
      dist: xenial
      sudo: required
      env:
        - MATRIX_EVAL="DOWNLOAD_ROCKSDB=ON && DOWNLOAD_CATCH=ON"

    - os: linux
      dist: xenial
      sudo: required
      env:
        - MATRIX_EVAL="TYPE=Debug && DOWNLOAD_ROCKSDB=ON && DOWNLOAD_CATCH=ON"

    - os: linux
      dist: xenial
      sudo: required
      env:
        - MATRIX_EVAL="sudo apt-get install -y clang-3.9 && CC=clang-3.9 && CXX=clang++-3.9 && DOWNLOAD_ROCKSDB=ON && DOWNLOAD_CATCH=ON"

    - os: linux
      dist: xenial
      sudo: required
      env:
        - MATRIX_EVAL="sudo apt-get install -y clang-5.0 && CC=clang-5.0 && CXX=clang++-5.0 && DOWNLOAD_ROCKSDB=ON && DOWNLOAD_CATCH=ON"

    - os: osx

    - os: osx
      env:
        - MATRIX_EVAL="TYPE=Debug"

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update -qq; sudo apt-get install libboost-filesystem-dev -y; else brew update; brew upgrade boost; brew install rocksdb; fi
  - eval "${MATRIX_EVAL}"

script:
  - mkdir -p .build
  - cd .build
  - cmake -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC -DCMAKE_BUILD_TYPE=${TYPE:-Release} -DDOWNLOAD_ROCKSDB=${DOWNLOAD_ROCKSDB:-ON} -DDOWNLOAD_CATCH=${DOWNLOAD_CATCH:-ON} ../
  - make -j 8
  - ./tests
